# Generated by Django 3.2.12 on 2024-05-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investiment',
            name='creation_date',
            field=models.DateField(verbose_name='Data de criação'),
        ),
    ]
