# Generated by Django 3.2.12 on 2024-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0002_alter_investiment_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investiment',
            name='investment_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo do Investimento'),
        ),
        migrations.AddField(
            model_name='investiment',
            name='investment_withdrawal',
            field=models.BooleanField(default=False, verbose_name='Saque do investimento'),
        ),
    ]
