# Generated by Django 3.2.12 on 2024-05-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_auto_20240521_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investiment',
            name='investment_balance',
        ),
    ]
