# Generated by Django 3.2.12 on 2024-05-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_remove_investiment_investment_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('withdrawal_date', models.DateField(verbose_name='Data do Saque')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='investment.investiment', verbose_name='Investmento')),
            ],
            options={
                'verbose_name': 'withdraw',
                'verbose_name_plural': 'withdraw',
            },
        ),
    ]
