# Generated by Django 3.2.12 on 2024-05-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_withdraw_withdraw_full_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
