# Generated by Django 3.2.12 on 2024-05-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_alter_withdraw_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='investiment',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo'),
        ),
    ]
