# Generated by Django 3.2.12 on 2024-05-22 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0009_investor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investiment',
            name='owner',
        ),
    ]
