# Generated by Django 3.2.12 on 2024-05-22 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0010_remove_investiment_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='investiment',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='investment.investor', verbose_name='proprietário'),
            preserve_default=False,
        ),
    ]
