# Generated by Django 3.2.12 on 2024-05-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_investiment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investor',
            name='email',
        ),
    ]
