# Generated by Django 3.2.12 on 2024-05-24 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_remove_investor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='investment.investiment', verbose_name='Investmento'),
        ),
    ]
